# Generated by Django 3.2.7 on 2021-10-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('matching_complete', models.IntegerField(default=0)),
                ('request_complete', models.IntegerField(default=0)),
                ('share_or_not', models.IntegerField(default=0)),
                ('post_time', models.DateTimeField()),
                ('text', models.CharField(max_length=100)),
                ('departure_place', models.CharField(max_length=100)),
                ('destination_place', models.CharField(max_length=100)),
                ('delivery_date', models.CharField(max_length=50)),
                ('asking_price', models.IntegerField()),
                ('driver_evaluation', models.FloatField()),
                ('client_evaluation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('is_driver', models.BooleanField(default=False)),
                ('hashed_pass', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('total_socore', models.FloatField(max_length=50)),
            ],
        ),

        
    ]
