# Generated by Django 3.2.7 on 2021-10-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_favorite_message_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='request',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
