# Generated by Django 3.2.7 on 2021-10-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211002_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='matching_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='share_or_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='hashed_pass',
            field=models.IntegerField(),
        ),
    ]
