# Generated by Django 3.2.7 on 2021-10-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211002_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='client_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.user_info'),
        ),
    ]
