# Generated by Django 3.2.7 on 2021-10-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_request_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_info'),
        ),
    ]
