# Generated by Django 3.2.7 on 2021-10-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_request_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('matching_complete', models.BooleanField(default=False)),
                ('request_complete', models.BooleanField(default=False)),
                ('share_or_not', models.BooleanField(default=False)),
                ('post_time', models.DateTimeField()),
                ('text', models.TextField(max_length=1000)),
                ('departure_place', models.CharField(max_length=100)),
                ('destination_place', models.CharField(max_length=100)),
                ('delivery_date', models.DateTimeField()),
                ('asking_price', models.IntegerField()),
                ('driver_evaluation', models.FloatField()),
                ('client_evaluation', models.FloatField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_info')),
            ],
        ),
        migrations.AlterField(
            model_name='favorite',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.requests'),
        ),
        migrations.AlterField(
            model_name='message',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.requests'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.requests'),
        ),
        migrations.DeleteModel(
            name='request',
        ),
    ]
