# Generated by Django 3.2.7 on 2021-10-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_message_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='text',
            new_name='mess',
        ),
    ]
